"""Add approvals column to escrow

Revision ID: 11fb35076ed6
Revises: 
Create Date: 2025-04-09 11:20:56.757102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fb35076ed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approvals', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.drop_column('approvals')

    # ### end Alembic commands ###
